### ISSUE TITLE
Relationship to livy-client in apache-incubator/livy

### ISSUE THREAD

**Issue by ericdill** [acroz/pylivy#33]
Hi @acroz,

What is the use-case overlap between `pylivy` and the built-in python client in [apache-incubator/livy](https://github.com/apache/incubator-livy/tree/master/python-api/src/main/python/livy)?

**Comment by acroz** [comment]
Hey @ericdill, the main difference is that `pylivy` orchestrates Spark code by sending 'statements' (code snippets) to Livy whereas AFACIT the client in [apache-incubator/livy](https://github.com/apache/incubator-livy/tree/master/python-api/src/main/python/livy) uses an undocumented (in the [REST docs](https://livy.incubator.apache.org/docs/latest/rest-api.html) or any other docs I could find) endpoint to dispatch whole Python files to be executed.

I needed a Python client at short (~1 day) notice which could execute Python code and retrieve the contents of server-side dataframes back into the client-side interpreter, similarly to how [sparkmagic](https://github.com/jupyter-incubator/sparkmagic) works. Combined with my unease at using an undocumented REST API, the Python client in [apache-incubator/livy](https://github.com/apache/incubator-livy/tree/master/python-api/src/main/python/livy) is not on PyPI, so I decided to reimplement a cleaned up version of sparkmagic's client (it's fairly coupled to the rest of the package) and put it on GitHub and PyPI.

**Comment by ericdill** [comment]
(disclosure: I am not an expert on the Livy Python API). It is not at all clear to me what problem the Livy Python API is solving. It is definitely poorly documented and there's no description of how to actually use it. If I was in your shoes, I would definitely write a wrapper too. It seems like the "official" API is using the `/sessions` endpoint [here](https://github.com/apache/incubator-livy/blob/master/python-api/src/main/python/livy/client.py#L431), but the way they construct the request object is pretty baffling. It does seem like they are at least using the `/sessions` endpoint though, so that's at least better than using an undocumented API 😁 

>  I decided to reimplement a cleaned up version of sparkmagic's client

Ahh, I see. So this is intended as a better Livy interaction than the way-too-magical sparkmagic kernel. I like the way that you have to be explicit here, calling out to Livy to send code over to Spark, instead of the way that sparkmagic does it where I'm never really sure where my code is running.

Do you use pylivy exclusively in place of sparkmagic now?

**Comment by acroz** [comment]
No actually, I still use sparkmagic for interactive work from Jupyter.

I don't use the full on Sparkmagic kernel, but I do use a normal kernel combined with explicitly creating a Livy session with the appropriate magic command and decorating specific cells to be run in the Livy session with the `%%spark` cell magic.

pylivy is what I use if I then want to take the code developed in Jupyter and use it in another context e.g. a script.

**Comment by ericdill** [comment]
> I don't use the full on sparkmagic kernel, but I do use a normal kernel combined with explicitly creating a Livy session with the appropriate magic command and decorating specific cells to be run in the Livy session with the %%spark cell magic.

Oh, that's clever.

> pylivy is what I use if I then want to take the code developed in Jupyter and use it in another context e.g. a script.

It seems like your primary use case is one of mixed local<>remote, thus desiring to use the `/sessions` endpoint. Do you have a use case for the `/batches` endpoint? This seems to be the way that you'd want to interact with livy in a more `spark-submit` type of way, though I haven't yet come across anyone using the `/batches` endpoint from Python. I wonder how useful adding a Python API for that endpoint would be. Do you have any thoughts on that endpoint?

**Comment by acroz** [comment]
If someone has a use case for the `/batches` endpoint I'd be happy to add it to this library, though I'm in no rush to add it personally - I feel it would be better to use something like Amazon EMR in this case, where I can tie the lifecycle of the Spark cluster to the task, thus minimising compute costs from not running idle clusters.

You're right that the mixed local / remote case is indeed my use case here (as inspired by sparkmagic as previous mentioned), though as above I'm happy to extend pylivy to other use cases that people might have.

**Comment by acroz** [comment]
Thanks to #60, batch sessions are now supported! 🎉
