### ISSUE TITLE
Request body only "kind" is supported why not all others (proxyUser,...heartbeatTimeoutInSecond) as input ? 

### ISSUE THREAD

**Issue by ramanapalakveety** [acroz/pylivy#34]
Only 'kind' is allowed as parameter, what about all other request body inputs supported by livy rest api.
Am I missing something here?

proxyUser | User to impersonate when starting the session | string
jars | jars to be used in this session | List of string
pyFiles | Python files to be used in this session | List of string
files | files to be used in this session | List of string
driverMemory | Amount of memory to use for the driver process | string
driverCores | Number of cores to use for the driver process | int
executorMemory | Amount of memory to use per executor process | string
executorCores | Number of cores to use for each executor | int
numExecutors | Number of executors to launch for this session | int
archives | Archives to be used in this session | List of string
queue | The name of the YARN queue to which submitted | string
name | The name of this session | string
conf | Spark configuration properties | Map of key=val
heartbeatTimeoutInSecond | Timeout in second to which session be orphaned | int

**Comment by acroz** [comment]
I just didn't get around to implementing them yet. Are there any in particular you need? I'm happy to extend the code to support them if it would be of use to you.

**Comment by ramanapalakveety** [comment]
We are using most of these parameters in our calls.
It would be great if we have these in the library.
If you can create any branch for this, I can help on test/fix issues and/or implement some.

Ramana

**Comment by acroz** [comment]
Sorry for not getting to this sooner - I've just merged PR #40 supporting the proxyUser and hope to implement others soon.

**Comment by parisni** [comment]
Hi
Looks to me that would be great if all those param would be available.
Maybe by passing a dict ?
Thanks

**Comment by acroz** [comment]
This has been implemented in release 0.5.0. Thanks for the suggestion!
