### ISSUE TITLE
Runtime error 'statement had no output' issue.

### ISSUE THREAD

**Issue by saivarunr** [acroz/pylivy#36]
Preface: Using livy with flask app, which is running via gunicorn, async worker, gevent worker.
All the services are dockerized, (flask/gunicorn, apache livy, spark).

Few times, I have observed that the library pylivy would throw Runtime error 'statement had no output', but, but, but, when I looked at the apache livy session output logs, the code would have executed with ok and would also have respective output in logs, tried to replicate this several times, was unlucky to replicate properly, but when I did, I found out that.
1) Apache livy logs were showing proper output, and successful execution of the code.
2) pylivy would throw 'statement had no output' in _execute method of session.py module, state was Available but output was None on pylivy, but output was available on the apache livy logs.

My two cents of thought, may be for few actions, output is delayed to the statement REST api, may we have to poll for a second or two to get response back.

Please help me fix this one! Thanks.

**Comment by saivarunr** [comment]
took liberty to put print statements in _execute method in 
the statement output was None but was available
`statement None StatementState.AVAILABLE`
the code was this
code `dataframe_90c66a67b8a64f1585d5113f5c899eb9.columns`


2018-11-06 10:50:48,833 - xvector - INFO - Exception in testest
Traceback (most recent call last):
  File "/root/sparkfile.py", line 1082, in execute_augment_function
    _columns = eval(session.run("{df}.columns".format(df=self.df)).text)
  File "/usr/local/lib/python3.6/site-packages/livy/session.py", line 117, in run
    output = self._execute(code)
  File "/usr/local/lib/python3.6/site-packages/livy/session.py", line 159, in _execute
    raise RuntimeError('statement had no output')

but see this.

![image](https://user-images.githubusercontent.com/20237860/48059969-91369f00-e1e0-11e8-8a5e-19a283eb206c.png)

**Comment by acroz** [comment]
Hi @saivarunr - sorry for not getting to this sooner!

Can you provide a minimal example that reproduces this? It might be useful to also tell which version of Livy you are using.

**Comment by saivarunr** [comment]
Hi @acroz Livy version is 0.5.0 the latest release, on spark 2.2.1.

The bug does not have a pattern to help reproduce it, occurs once in a very long run, yes it is kind of frustrating to understand from a developing point of view, but it did occur. Since I did not get an immediate response from your community, I had to implement the fix on our side which is by adding few extra lines of code, that fixed it, you can check that part of code [here](https://github.com/saivarunr/pylivy/blob/master/pylivy/session.py#L159).(https://github.com/saivarunr/pylivy/blob/master/pylivy/session.py#L159)
And we are using the same code in production and the bug never comes back.

**Comment by acroz** [comment]
Thanks, your patch was very instructive. I've implemented a slightly different mitigation in PR #41 that uses the existing loop to keep polling if the statement state is 'available' but no output is set. Can you have a look and check that it addresses your issue?

**Comment by saivarunr** [comment]
@acroz Yes, that should be it. Closing this.

**Comment by acroz** [comment]
Great, I've released this with 0.4.1
