### ISSUE TITLE
Can not import LivySession

### ISSUE THREAD

**Issue by Dheeraj-Arremsetty** [acroz/pylivy#48]
Hi All,
I am trying to programmatically use livy and access remote spark context.
I have used below command to install livy as mentioned in docs:

`pip install -U livy --user`

But when I try to import LivySession I see below error:

`>>> from livy import LivySession
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/...../Library/Python/2.7/lib/python/site-packages/livy/__init__.py", line 1, in <module>
    from livy.session import LivySession  # noqa: F401
  File "/Users/....../Library/Python/2.7/lib/python/site-packages/livy/session.py", line 22
    dataframe_name: str, session_kind: SessionKind
                  ^
SyntaxError: invalid syntax
`
Is it anything I am doing wrong ??

**Comment by acroz** [comment]
Hi, thanks for trying out pylivy!

Looks like you're trying to use pylivy with Python 2.7, whereas only 3.6+ is supported. The codebase uses some language features (type hints specifically) that don't exist in 2.7, hence the SyntaxError.

If you're not familiar with managing multiple versions of Python on your system, I suggest taking a look at pyenv or conda.

**Comment by Dheeraj-Arremsetty** [comment]
Thank you for the response. I have not seen anywhere in the doc that pylivy supports python3, or maybe it is mentioned and I missed it.
It really works with Python3.
Thanks again.

**Comment by acroz** [comment]
Thanks, that's useful feedback. I've updated the README and docs to clarify the supported Python versions.
