### ISSUE TITLE
Livy Example for Python

### ISSUE THREAD

**Issue by danielhanbitlee** [acroz/pylivy#59]
Hi,

I am having a hard time getting livy running on my local machine. I have Windows 10, Python 3.6, and pyspark 2.4.1, and livy 0.5.0. I have a csv file that I want to read in with pyspark. Can someone show me simple steps of using livy to do this? I'm trying to see if livy is a good option to be able to run spark code from web applications.

**Comment by acroz** [comment]
Hi Daniel,

I've unfortunately not got any experience with setting up Spark or Livy on Windows - I've mainly used with it through vendor-configured distributions like Amazon EMR or Cloudera. For support with setup, I suggest asking on the Livy users mailing list (see https://livy.apache.org/community/).

If you're looking for an example on building a web application interfacing with Spark through Livy, I've given a talk on this that you can watch here (the app stuff is at the end): 

https://www.youtube.com/watch?v=iHg0NwEjbxk

However, if you're writing a web application in Javascript (and not a Python tool like Plotly Dash in my talk), you might want to cut out the middle man and call the [Livy HTTP API](https://livy.apache.org/docs/latest/rest-api.html) directly from Javascript.

**Comment by danielhanbitlee** [comment]
Sounds good. Thanks for the helpful response.
