### ISSUE TITLE
Support for headers in requests

### ISSUE THREAD

**Issue by TorMcK** [acroz/pylivy#64]
Hi,
I have a requirement to use two headers when calling my livy endpoint:
"Authorization" for use with a token 
and 
"X-Requested-By" which is required because csrf is enabled in livy.

I have modified my local code pylivy code to enable headers (only some small changes)
Should I create a pull request to merge this with the code or is it a design choice to not include headers?

**Comment by acroz** [comment]
This is now resolved in [0.7.0](https://pypi.org/project/livy/0.7.0/) thanks to #77.
