### ISSUE TITLE
Transferring objects from local python context into PySpark context

### ISSUE THREAD

**Issue by gthomas-slack** [acroz/pylivy#88]
Hi @acroz! - sparkmagic has this very [cool feature](https://github.com/jupyter-incubator/sparkmagic/blob/9ba4d4f0415c16f2f1c74c2c2478140b7dde222c/sparkmagic/sparkmagic/magics/sparkmagicsbase.py#L51) which allows you to transfer python objects like a pandas dataframe from the local python context into the remote spark context via Livy (eg. the pandas dataframe becomes a pyspark dataframe in the spark context).

I was thinking about looking into trying to add some similar functionality for `pylivy`, but before I start looking into it I wanted to see if you have already looked into this at all, or have any thoughts on it?

Thanks!

**Comment by acroz** [comment]
Hey, this sounds like a cool feature, and a very useful addition!

If I understand correctly, this sounds like it would do the inverse of `livy.session.LivySession.read`, which retrieves a Spark dataframe as a Pandas DataFrame locally. I've not looked into implementing the upload, but I would look at implementing it in a similar way to how `read` works.

I imagine this would result in a method like:

```python
class LivySession:
    ...
    def write(self, dataframe_name: str, dataframe: pandas.DataFrame) -> None:
        ...
```

I'm not convinced that the naming of these methods as `read` and `write` are the best (`read` was probably decided in the late night coding session that hacked together the first version of this library and I am not wedded to it) - I wonder would it make sense to rename these to `download` and `upload` or something else suitable? Keen for your thoughts on this. (If we did rename them we could leave `read` as an alias with a deprecation warning).

Happy to help with this over the coming weeks, especially with a bit more free time over the holidays!

**Comment by acroz** [comment]
@gthomas-slack If you're interested in developing this I'm happy to leave it up to you, otherwise I may spend a bit of time on it myself over the next week or two. Please let me know your preference!

**Comment by gthomas-slack** [comment]
I likely won’t have time to look into it over the next couple of weeks,
please go ahead, thanks!

**Comment by acroz** [comment]
@gthomas-slack I've opened #93 to implement this, and renamed read/write to download/upload as mentioned. Can you have a look and offer any comments, especially on the naming issue?

**Comment by gthomas-slack** [comment]
Hi @acroz Awesome! Sorry for the delayed response, I am just getting back to work today. I'll take a look soon!

**Comment by gthomas-slack** [comment]
Hi @acroz So sorry for the late response on this, I just wanted to say that we have started using this feature internally, and it's working great. Thanks so much for adding it, very much appreciated 🙇
